[package]
name = "ariel-os-scum"
version = "0.5.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ariel-os-embassy-common = { workspace = true }
cortex-m-rt = { workspace = true, features = ["device"] }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
scum-sdk-sys = { path = "../lib/scum-sdk-sys" }

[lints]
workspace = true
